### ISSUE TITLE
is this still getting updates?

### ISSUE THREAD

**Issue by super-lurker** [EIGHTFINITE/jdownloader-portable#1]
is this still getting updates?

**Comment by kevinvanrijn** [comment]
The application should automatically update after running it once.

The server I set up to keep it updated here imploded a while ago. I haven't found the time to set it up again. I'll try to do it this weekend.

**Comment by kevinvanrijn** [comment]
The server is now back up and running. It just updated JDownloader in 7e4988f21359a43c8defb2e56aa7235351d8e762 as well. It should now be protected from imploding again as well but I'll keep an eye on it for a couple days to make sure.

**Comment by super-lurker** [comment]
my man!! you're a hero for doing this, this is the only portable jd working atm (afaik) 
keep it alive.
thanks
