### ISSUE TITLE
how to automatic update?

### ISSUE THREAD

**Issue by tuchit** [EIGHTFINITE/jdownloader-portable#2]
its not official supported by PortableApps.com Platform
so how to automatic update?

**Comment by kevinvanrijn** [comment]
I'm not using PortableApps.com for the actual updates to JDownloader.

JDownloader can already keep itself up-to-date on its own. With or without the help of PortableApps.com. [How is explained here.](http://jdownloader.org/knowledge/wiki/problems/plugin-update)

I'm keeping the repo updated to avoid users having to download a ton of updates when they first download one of the zips from the [releases](https://github.com/EIGHTFINITE/jdownloader-portable/tags).

EDIT: This is now using GitHub Actions the file for which can be found here: https://github.com/EIGHTFINITE/jdownloader-portable/blob/master/.github/workflows/update.yml
