### ISSUE TITLE
Continues to check update servers despite disabling settings

### ISSUE THREAD

**Issue by i010011010** [EIGHTFINITE/jdownloader-portable#5]
org.appwork.updatesys.client.defaultimpl.http.NoConnectionException: org.jdownloader.update.lastchance.FailedException: org.appwork.updatesys.client.defaultimpl.http.NoConnectionException: Could not Connect to http://update.appwork.org/jcgi/etc

I disabled all advanced settings matching UpdateSettings but the client persists in trying to reach an outbound site.

Would also like to know how to disable outbound traffic attempts to

ipcheck0.jdownloader[.]org through ipcheck4.jdownloader[.]org

**Comment by kevinvanrijn** [comment]
I don't know enough about the settings to help you with this. Reminder that this is the repository for the portable wrapper not JDownloader itself.

Please create a thread on https://board.jdownloader.org/ instead to receive support for JDownloader.

**Comment by i010011010** [comment]
Gotcha, well thanks for putting this together in a portable bundle that doesn't require internet to run.  It's been a huge help.
